apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #Volume can be read from or written to, from one node at one time.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #Volume can be read from or written to, from one node at one time.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-claim
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #Volume can be read from or written to, from one node at one time.